### ISSUE TITLE
Raised an error library "libnative_with_opencv.so" not found

### ISSUE THREAD

**Issue by mukunthan007** [fzyzcjy/flutter_cpp_with_opencv#5]
The error show in a terminal as 
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following ArgumentError was thrown building MyApp(dirty, state: _MyAppState#c8a94):
Invalid argument(s): Failed to load dynamic library 'libnative_with_opencv.so': dlopen failed:
library "libnative_with_opencv.so" not found

The relevant error-causing widget was:
  MyApp MyApp:file:///D:/flutter_apps/flutter_cpp_with_opencv/example/lib/main.dart:5:10
  
  
  Have done the steps mentioned below in the stackoverflow for android only
  https://stackoverflow.com/questions/63127202/how-to-use-opencv-4-in-native-c-of-flutter-in-2022-support-flutter-2-0-3-0

**Comment by fzyzcjy** [comment]
Could you please firstly check your folder to see whether the so is there?

**Comment by mukunthan007** [comment]
There no so file in the folder

**Comment by fzyzcjy** [comment]
Then maybe need to check why it is not compiled / copied to there, e.g. check the logs etc

**Comment by mukunthan007** [comment]
Can you please tell me where can I find the log file ?. I am newbiew to the flutter

**Comment by fzyzcjy** [comment]
Just look at flutter logs
